try again

diff --git a/.github/workflows/test_workflow.yml b/.github/workflows/test_workflow.yml
--- a/.github/workflows/test_workflow.yml
+++ b/.github/workflows/test_workflow.yml
@@ -13,52 +13,37 @@ on:
     branches:
       - master
   workflow_dispatch:
-  schedule:
-    - cron: "*/5 * * * *"
+    inputs:
+      debug_enabled:
+        type: boolean
+        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
+        required: false
+        default: false
 
 env:
   # only run tmate if manually invoked and debug_enabled == true or a previous step failed
-  SETUP_TMATE: ${{ (((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) || (github.job.status != 'success')) && (github.repository_owner == 'nilsnolde') }}
+  SETUP_TMATE: ${{ ((github.event_name == 'workflow_dispatch') && (github.event.inputs.debug_enabled == 'true')) }}
   # only publish to PyPI on tags, schedule or workflow_dispatch (only on master!)
   PUBLISH_PYPI: ${{ (startsWith(github.ref, 'refs/tags') || (github.event_name == 'schedule') || ((github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/master'))) && (github.repository_owner == 'nilsnolde') }}
 
 jobs:
-  publish_pypi:
-    name: Whether to publish PyPI
-    runs-on: ubuntu-latest
-    steps:
-      - run: echo "Are we publishing to PyPI?\n\$ ${{ env.PUBLISH_PYPI }}"
-    outputs:
-      PUBLISH_PYPI: ${{ env.PUBLISH_PYPI }}
-
   test:
     name: test tag stuff
     runs-on: ubuntu-latest
-    needs: [publish_pypi]
     steps:
       - uses: actions/checkout@v4
 
-      - name: Bla
+      - name: exit
         run: |
-          echo "VALHALLA_RELEASE_PKG=bla" >> $GITHUB_ENV
+          echo "${{ env.SETUP_TMATE }}"
+          exit 1
 
       - name: Determine package to publish
-        if: ${{ env.VALHALLA_RELEASE_PKG }}
+        if: ${{ env.SETUP_TMATE == 'true' || failure() }}
         run: |
-          echo "${{ needs.publish_pypi.outputs.PUBLISH_PYPI }}"
-          echo "pkg release: $VALHALLA_RELEASE_PKG"
-          echo "pkg release: ${{ env.VALHALLA_RELEASE_PKG }}"
-          echo "pkg release: ${{ github.env }}"
-          echo "Publish PyPI: ${{ env.PUBLISH_PYPI }}"
-          echo "${{ github.ref }}"
-          echo "${{ github.event_name }}"
+          echo "${{ env.SETUP_TMATE }}"
+          echo "${{ job.status == 'success' }}"
+          echo "${{ job.status }}"
           echo "${{ github.repository_owner }}"
-          echo "${{ startsWith(github.ref, 'refs/tags') || (github.event_name == 'schedule') }}"
-          echo "${{ startsWith(github.ref, 'refs/tags') || (github.event_name == 'schedule') || ((github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/master')) }}"
-          echo "${{ (startsWith(github.ref, 'refs/tags') || (github.event_name == 'schedule') || ((github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/master'))) && (github.repository_owner == 'nilsnolde') }}"
-  test2:
-    runs-on: ubuntu-latest
-    needs: [publish_pypi]
-    if: ${{ needs.publish_pypi.outputs.PUBLISH_PYPI == 'true' }}
-    steps:
-      - run: echo "${{ needs.publish_pypi.outputs.PUBLISH_PYPI }}"
+          echo "${{ github.repository_owner == 'nilsnolde' }}"
+          echo "${{ (env.SETUP_TMATE == 'true') || (job.status == 'failure' && (github.repository_owner == 'nilsnolde')) }}"
